### ISSUE TITLE
Mac環境での動作しない件について

### ISSUE THREAD

**Issue by ikuo0** [ikuo0/ebiten_stg#1]
Macで動かないようなので修正していきたいと思います。

**Comment by ikuo0** [comment]
紛らわしい話ですが件のログは正常終了時にも出ます
＞2016-10-23 17:13:07.0792 +0900 JST changer#Apply illegal scen name exit

終了させる処理が無いのでシーン切り替えのエラーを出すことで異常終了させています。
ですので何故か終了処理（メニューでExitの選択）と同等の操作が行われているようです。
もう少し詳細なログが出るように修正します、しばしお待ちを…

**Comment by hajimehoshi** [comment]
了解です。お待ちしています。

**Comment by hajimehoshi** [comment]
> 2016-10-23 17:13:07.0792 +0900 JST changer#Apply illegal scen name exit

改めて見たのですが、これ時刻から察するに自分のログではなくて、もともと入ってたやつですね。 log.txt は .gitignore に追加するのが良いと思います。

**Comment by hajimehoshi** [comment]
#4 の修正で Mac でも動くようになりました。

**Comment by ikuo0** [comment]
失礼しました　＞log.txt
ignoreしておきます。

> 修正
ありがとうございます、パスの問題だったんですね…
